import '@testing-library/jest-dom/vitest';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, render, waitFor } from '@testing-library/react';

declare global {
  // eslint-disable-next-line no-var
  var __ANTD_LAST_CONFIG_PROVIDER_PROPS__: unknown;
}

vi.mock('antd', async () => {
  const React = (await import('react')).default;
  return {
    ConfigProvider: (props: unknown) => {
      globalThis.__ANTD_LAST_CONFIG_PROVIDER_PROPS__ = props;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      return React.createElement(React.Fragment, null, (props as any).children);
    },
    theme: {
      defaultAlgorithm: 'default',
      darkAlgorithm: 'dark'
    }
  };
});

const React = (await import('react')).default;
const { FarmProvider } = await import('../src/react');

function getLastAntdTheme(): any {
  const props = globalThis.__ANTD_LAST_CONFIG_PROVIDER_PROPS__ as any;
  return props?.theme;
}

afterEach(() => {
  cleanup();
  delete (globalThis as any).__ANTD_LAST_CONFIG_PROVIDER_PROPS__;
  document.documentElement.removeAttribute('data-theme');
});

describe('FarmProvider', () => {
  it('默认 scope=document：设置并卸载还原 html[data-theme]', async () => {
    const { unmount } = render(
      React.createElement(FarmProvider, { mode: 'dark' }, React.createElement('div', { 'data-testid': 'child' }))
    );

    await waitFor(() => expect(document.documentElement).toHaveAttribute('data-theme', 'dark'));

    unmount();
    expect(document.documentElement).not.toHaveAttribute('data-theme');
  });

  it('scope=document：卸载时恢复之前的 html[data-theme]', async () => {
    document.documentElement.setAttribute('data-theme', 'light');

    const { unmount } = render(
      React.createElement(FarmProvider, { mode: 'dark' }, React.createElement('div', { 'data-testid': 'child' }))
    );

    await waitFor(() => expect(document.documentElement).toHaveAttribute('data-theme', 'dark'));

    unmount();
    expect(document.documentElement).toHaveAttribute('data-theme', 'light');
  });

  it('scope=wrap：不修改 html[data-theme]，但会包裹 data-theme 容器', () => {
    document.documentElement.setAttribute('data-theme', 'light');

    const { container } = render(
      React.createElement(
        FarmProvider,
        { scope: 'wrap', mode: 'dark' },
        React.createElement('div', { 'data-testid': 'child' })
      )
    );

    expect(document.documentElement).toHaveAttribute('data-theme', 'light');
    const wrapper = container.querySelector('div[data-theme="dark"]');
    expect(wrapper).toBeInTheDocument();
    expect(wrapper?.querySelector('[data-testid="child"]')).toBeInTheDocument();
  });

  it('默认会注入 tokensCss，传空字符串可关闭注入', () => {
    const { container: container1, unmount: unmount1 } = render(
      React.createElement(FarmProvider, null, React.createElement('div', { 'data-testid': 'child' }))
    );
    const style1 = container1.querySelector('style');
    expect(style1).toBeInTheDocument();
    expect(style1?.textContent).toContain('Auto-generated by @farm-design-system/theme');
    unmount1();

    const { container: container2 } = render(
      React.createElement(FarmProvider, { tokensCss: '' }, React.createElement('div', { 'data-testid': 'child' }))
    );
    expect(container2.querySelector('style')).not.toBeInTheDocument();
  });

  it('默认注入 antdTheme[mode] 并自动选择 algorithm，且支持合并覆盖', () => {
    render(
      React.createElement(
        FarmProvider,
        {
          mode: 'light',
          antdTheme: {
            algorithm: 'override',
            token: { colorPrimary: '#fff' },
            components: { Button: { colorPrimary: '#000' } }
          } as any
        },
        React.createElement('div', { 'data-testid': 'child' })
      )
    );

    const theme = getLastAntdTheme();
    expect(theme).toBeTruthy();
    expect(theme.algorithm).toBe('override');
    expect(theme.token?.colorPrimary).toBe('#fff');
    expect(theme.components?.Button?.colorPrimary).toBe('#000');
  });

  it('mode=dark 默认选择 dark algorithm', () => {
    render(React.createElement(FarmProvider, { mode: 'dark' }, React.createElement('div', { 'data-testid': 'child' })));
    const theme = getLastAntdTheme();
    expect(theme.algorithm).toBe('dark');
  });
});
